"use strict";
var s=Object.defineProperty;var M=Object.getOwnPropertyDescriptor;var k=Object.getOwnPropertyNames;var T=Object.prototype.hasOwnProperty;var y=(e,a)=>{for(var i in a)s(e,i,{get:a[i],enumerable:!0})},S=(e,a,i,o)=>{if(a&&typeof a=="object"||typeof a=="function")for(let n of k(a))!T.call(e,n)&&n!==i&&s(e,n,{get:()=>a[n],enumerable:!(o=M(a,n))||o.enumerable});return e};var A=e=>S(s({},"__esModule",{value:!0}),e);var I={};y(I,{MATCHMAKER_GAMEMODES:()=>u,MATCHMAKER_REGIONS:()=>C,fetchGame:()=>R});module.exports=A(I);var d=require("./preload"),p=require("./utils");const u=["Free for All","Team Deathmatch","Hardpoint","Capture the Flag","Parkour","Hide & Seek","Infected","Race","Last Man Standing","Simon Says","Gun Game","Prop Hunt","Boss Hunt","Classic FFA","Deposit","Stalker","King of the Hill","One in the Chamber","Trade","Kill Confirmed","Defuse","Sharp Shooter","Traitor","Raid","Blitz","Domination","Squad Deathmatch","Kranked FFA","Team Defender","Deposit FFA","Chaos Snipers","Bighead FFA"],C=["MBI","NY","FRA","SIN","DAL","SYD","MIA","BHN","TOK","BRZ","AFR","LON","CHI","SV","STL","MX"];function D(e){return u[e]}function F(e,a,i){return`Game found! ${e.gameID} (${a}/${i} games meet criteria)
	
	Region: ${e.region}
	Map: ${e.map}
	Gamemode: ${e.gamemode}
	Players: ${e.playerCount}/${e.playerLimit}
	Time remaining: ${(0,p.secondsToTimestring)(e.remainingTime)}
	
	Join game?`}async function R(e){const a={regions:e.matchmaker_regions,gameModes:e.matchmaker_gamemodes,minPlayers:e.matchmaker_minPlayers,maxPlayers:e.matchmaker_maxPlayers,minRemainingTime:e.matchmaker_minRemainingTime},o=await(await fetch(`https://matchmaker.krunker.io/game-list?hostname=${window.location.hostname}`)).json(),n=[];for(const t of o.games){const r=t[0],c=r.split(":")[0],m=t[2],l=t[3],f=t[4].i,g=D(t[4].g),h=t[5];!a.regions.includes(c)||!a.gameModes.includes(g)||m<a.minPlayers||m>a.maxPlayers||h<a.minRemainingTime||m===l||window.location.href.includes(r)||n.push({gameID:r,region:c,playerCount:m,playerLimit:l,map:f,gamemode:g,remainingTime:h})}if(n.length>0){const t=n[Math.floor(Math.random()*n.length)];confirm(F(t,n.length,o.games.length))&&(window.location.href=`https://krunker.io/?game=${t.gameID}`)}else alert("Couldn't find any games matching your criteria. Please change them or try again later."),d.strippedConsole.log(a)}0&&(module.exports={MATCHMAKER_GAMEMODES,MATCHMAKER_REGIONS,fetchGame});
