"use strict";
var f=Object.defineProperty;var U=Object.getOwnPropertyDescriptor;var b=Object.getOwnPropertyNames;var j=Object.prototype.hasOwnProperty;var T=(r,t)=>{for(var s in t)f(r,s,{get:t[s],enumerable:!0})},I=(r,t,s,e)=>{if(t&&typeof t=="object"||typeof t=="function")for(let n of b(t))!j.call(r,n)&&n!==s&&f(r,n,{get:()=>t[n],enumerable:!(e=U(t,n))||e.enumerable});return r};var O=r=>I(f({},"__esModule",{value:!0}),r);var g=(r,t,s)=>{if(!t.has(r))throw TypeError("Cannot "+s)};var d=(r,t,s)=>(g(r,t,"read from private field"),s?s.call(r):t.get(r)),P=(r,t,s)=>{if(t.has(r))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(r):t.set(r,s)},m=(r,t,s,e)=>(g(r,t,"write to private field"),e?e.call(r,s):t.set(r,s),s);var M={};T(M,{su:()=>i});module.exports=O(M);var a=require("fs"),h=require("path"),k=require("electron"),l=require("./preload"),y=require("./utils"),S=require("./userscriptvalidators"),c;const i={userscriptsPath:"",userscriptTrackerPath:"",userscriptPrefsPath:"",userscripts:[],userscriptTracker:{}},v=(r,t)=>{alert(`Userscript '${t}' had an error:

${r.toString()}

Please fix the error, disable the userscript in the 'tracker.json' file or delete it.
Feel free to check console for stack trace`)};class A{constructor(t){P(this,c,void 0);this.runAt="document-end";if(this.hasRan=!1,m(this,c,!1),this.name=t.name,this.fullpath=t.fullpath,this.meta=!1,this.unload=!1,this.settingsPath=t.settingsPath,this.content=(0,a.readFileSync)(this.fullpath,{encoding:"utf-8"}),this.content.startsWith('"use strict"')&&m(this,c,!0),this.content.includes("// ==UserScript==")&&this.content.includes("// ==/UserScript==")){const s=require("userscript-meta");let e=this.content.split(`
`);e=e.length===1?[e]:e;const n=e.findIndex(o=>o.includes("// ==UserScript==")),u=e.findIndex(o=>o.includes("// ==/UserScript=="));if(n!==-1&&u!==-1){e=e.slice(n,u+1).join(`
`),this.meta=s.parse(e);for(const o of Object.keys(this.meta)){const p=this.meta[o];Array.isArray(p)&&(this.meta[o]=p[p.length-1])}"run-at"in this.meta&&this.meta["run-at"]==="document.start"&&(this.runAt="document-start")}}}load(){try{const s=new Function(this.content).apply({unload:!1,settings:{},_console:l.strippedConsole,_css:y.userscriptToggleCSS});if(typeof s<"u"&&("unload"in s&&(this.unload=s.unload),"settings"in s&&(this.settings=s.settings)),Object.keys(this.settings).length>0&&(0,a.existsSync)(this.settingsPath))try{var t=JSON.parse((0,a.readFileSync)(this.settingsPath,"utf-8"));Object.keys(t).forEach(e=>{(0,S.customSettingSavedJSONIsNotMalformed)(e,this.settings,t)&&this.settings[e].changed(t[e])})}catch{}l.strippedConsole.log(`%c[cs]${d(this,c)?"%c[strict]":"%c[non-strict]"} %cran %c'${this.name.toString()}' `,"color: lightblue; font-weight: bold;",d(this,c)?"color: #62dd4f":"color: orange","color: white;","color: lightgreen;")}catch(s){v(s,this.name),l.strippedConsole.error(s)}}}c=new WeakMap,k.ipcRenderer.on("main_initializes_userscripts",(r,t)=>{i.userscriptsPath=t.userscriptsPath,i.userscriptTrackerPath=(0,h.resolve)(i.userscriptsPath,"tracker.json"),i.userscriptPrefsPath=t.userscriptPrefsPath,i.userscripts=(0,a.readdirSync)(i.userscriptsPath,{withFileTypes:!0}).filter(e=>e.name.endsWith(".js")).map(e=>new A({name:e.name,settingsPath:(0,h.resolve)(i.userscriptPrefsPath,e.name.replace(/.js$/,".json")),fullpath:(0,h.resolve)(i.userscriptsPath,e.name).toString()}));const s={};i.userscripts.forEach(e=>{s[e.name]=!1}),Object.assign(s,JSON.parse((0,a.readFileSync)(i.userscriptTrackerPath,{encoding:"utf-8"}))),(0,a.writeFileSync)(i.userscriptTrackerPath,JSON.stringify(s,null,2),{encoding:"utf-8"}),i.userscriptTracker=s,i.userscripts.forEach(e=>{if(s[e.name])if(e.runAt==="document-start")e.load();else{const n=()=>e.load();try{document.removeEventListener("DOMContentLoaded",n)}catch{}document.addEventListener("DOMContentLoaded",n,{once:!0})}})});0&&(module.exports={su});
